[versions]
skia = "0.9.18"
pretty-log = "1.4"
bindables = "1.1"
kotlinx-serialization = "1.3.0"
ktoml = "0.5.1"

[libraries]
kotlinx-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
logger = { group = "cz.lukynka", name = "pretty-log", version.ref = "pretty-log" }
bindables = { group = "cz.lukynka", name = "kotlin-bindables", version.ref = "bindables" }
ktoml-core = { group = "com.akuleshov7", name = "ktoml-core", version.ref = "ktoml" }
ktoml-file = { group = "com.akuleshov7", name = "ktoml-file", version.ref = "ktoml" }
skio-awt = { group = "org.jetbrains.skiko", name = "skiko-awt", version.ref = "skia" }
skiko-awt-runtime-all = { group = "org.jetbrains.skiko", name = "skiko-awt-runtime-all", version.ref = "skia" }
[bundles]
serialization = ["kotlinx-core", "kotlinx-json", "ktoml-core", "ktoml-file"]
skia = ["skio-awt", "skiko-awt-runtime-all"]